/*
 * This source file was generated by the Gradle 'init' task
 */
package calculator;

import java.util.Scanner;

import calculator.enums.Operator;
import calculator.exception.DivideByZeroException;
import calculator.exception.UnknownOperatorException;

public class App {
    public static void main(String[] args) {
        boolean isLoop = true;
        Scanner sc = new Scanner(System.in);
        Calculator calculator = new Calculator();
        while (isLoop) {
            System.out.print("첫 번째 정수: ");
            int first = sc.nextInt();
            System.out.print("두 번째 정수: ");
            int second = sc.nextInt();
            System.out.print("연산자 (+, -, *, /): ");
            String operatorString = sc.next();
            try {
                Operator operator = Operator.fromSymbol(operatorString);
                double result = calculator.calculate(first, second, operator);
                System.out.println("결과: " + String.format("%.2f", result));
            } catch (DivideByZeroException e) {
                System.out.println("오류: " + e.getMessage());
                continue;
            } catch (UnknownOperatorException e) {
                System.out.println("오류: " + e.getMessage());
                continue;
            }
            System.out.print("종료하시겠습니까?(exit): ");
            String exit = sc.next();
            if (exit.equals("exit")) {
                isLoop = false;
            }
        }
        sc.close();

        // searchBiggerThan 예시
        searchBiggerThanExample();
    }

    public static void searchBiggerThanExample() {
        Calculator calculator = new Calculator();

        // 참조형이므로 getResults()를 통해 접근
        calculator.getResults().add(10.0);
        calculator.getResults().add(20.0);
        calculator.getResults().add(30.0);
        calculator.getResults().add(40.0);
        calculator.getResults().add(50.0);
        
        double value = 25.0;
        System.out.println("값: " + value);
        System.out.println("더 큰 값: " + calculator.searchBiggerThan(value));
    }
}
